const SHORT_CONFIG_OPTION = '-c';
const LONG_CONFIG_OPTION = '--config';
const SHORT_INPUT_OPTION = '-i';
const LONG_INPUT_OPTION = '--input';
const SHORT_OUTPUT_OPTION = '-o';
const LONG_OUTPUT_OPTION = '--output';
const SEPARATOR_IN_CONFIG = '-';
const DECODING_FLAG = '0';
const ENCODING_FLAG = '1';
const MAX_LENGTH_CONFIG_ITEM = 2;

module.exports = {
    ENCODING_FLAG,
    DECODING_FLAG,
    MAX_LENGTH_CONFIG_ITEM,
    SHORT_CONFIG_OPTION,
    LONG_CONFIG_OPTION,
    SHORT_INPUT_OPTION,
    LONG_INPUT_OPTION,
    SHORT_OUTPUT_OPTION,
    LONG_OUTPUT_OPTION,
    SEPARATOR_IN_CONFIG,
};
